### ISSUE TITLE
upgrade from mysql upgrade

### ISSUE THREAD

**Issue by grooverdan** [ottok/mariadb-10.0#22]
Is it possible to check if the previous version was mysql?

If so...

MDEV-6916 (near bottom)

mysql_upgrade  --upgrade-from-mysql

**Comment by ottok** [comment]
Not to my knowledge. We could of course try to invent some clever test for some signs of previous installs, but maybe it is better to fix as upstream as possible to that "--upgrade-from-mysql" would be automatic if the database itself looks like it was from a non-MariaDB install.

**Comment by grooverdan** [comment]
looking back, i've found the uncommitted patch which does detect and invoke the update automaticly though mysql_upgrade and does detect if mysql was the origin.
